### ISSUE TITLE
Found a possible security concern

### ISSUE THREAD

**Issue by benharvie** [unilogies/bumsys#1]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@krizzsk) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by kmkalam24** [comment]
Hello, 
Thank you so much for giving your attention. 

I have created a `SECURITY.md` with a short of necessary information how do you report the security issue.

Looking forward to hearing from you soon. 

Thank you again
