### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by jplopezy** [unilogies/bumsys#2]
I installed the database as per the documentation and also attempted to consume it with the specified host, but encountered an error in PHP.

Can you help me?

Error :

[Sat Feb 25 17:37:15.427010 2023] [php:error] [pid 48021] [client 192.168.224.1:53101] PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /var/www/html/bumsys/core/functions.php:2127\nStack trace:\n#0 /var/www/html/bumsys/core/functions.php(50): get_options()\n#1 /var/www/html/bumsys/core/loader.php(36): root_domain()\n#2 /var/www/html/bumsys/index.php(15): require('...')\n#3 {main}\n  thrown in /var/www/html/bumsys/core/functions.php on line 2127

**Comment by kmkalam24** [comment]
What PHP version are you using?

**Comment by kmkalam24** [comment]
and please use the latest version.
